name: labextension

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Miniconda
        shell: bash
        run: |
          MINICONDA_FILENAME=Miniconda3-latest-Linux-x86_64.sh
          curl -o $MINICONDA_FILENAME "https://repo.continuum.io/miniconda/$MINICONDA_FILENAME"
          bash ${MINICONDA_FILENAME} -b -f -p $HOME/miniconda3
      - name: Setup paths
        shell: bash
        run: |
          echo "$HOME/miniconda3/bin" >> $GITHUB_PATH
          echo "$GITHUB_PATH"
          echo "$HOME/miniconda3/bin"
      - name: Install node
        run: |
          conda install -c conda-forge nodejs=17.4
      - name: Install jupyterlab
        run: |
          conda install jupyterlab=3.2.9
      - name: Install conda-build
        run: |
          conda install -y -c conda-forge conda-build
      - name: Build the extension
        run: |
          echo "$GITHUB_PATH"
          ls $HOME/miniconda3/bin
          jlpm
          jlpm run build
