name: labextension 

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: labextension
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7 
      - name: Test Conda
        run: | 
          conda --version 
      - name: Download Node
        run: conda install -y -c conda-forge nodejs=17.4.0
      - name: Download JupyterLab
        run: conda install -y jupyterlab=3.2.9
      - name: Build Extension
        run: |
          jlpm
          jlpm run build
      - name: List packages
        run: ls
