name: labextension 

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: labextension
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7 
      - name: Test Conda
        run: $CONDA/bin/conda --version 
      - name: Download Node
        run: $CONDA/bin/conda install -y -c conda-forge nodejs=17.4.0
      - name: Download JupyterLab
        run: $CONDA/bin/conda install -y jupyterlab=3.2.9
